---
title: "test"
author: "Mansoor Baba Shaik"
date: "November 28, 2016"
output: pdf_document
---

```{r, warning=FALSE, message=FALSE}
rm(list=ls())
setwd("~/IS665/risk")

classify_risk = read.csv("ClassifyRisk_historical.csv", header=TRUE, sep=",", dec=".")

require(ggplot2)

ggplot(data=classify_risk) + geom_point(aes(x=age, y=income, color=risk)) + theme_light()

```

```{r, warning=FALSE, message=FALSE}
require(class)
require(magrittr)

summary(classify_risk)

n.classify_risk <- data.frame(sapply(classify_risk[,c(2,3,5)], function(x) {
(x - min(x))/(max(x) - min(x))
}))

head(n.classify_risk)

```

```{r, warning=FALSE, message=FALSE}
# Split
set.seed(1234) # makes it repeatable
ind <- sample(2, nrow(classify_risk), replace = TRUE, prob = c(0.67, 0.33))
## Data Split

n.classify_risk<-data.frame(classify_risk[,"mortgage"],n.classify_risk[,1:2],classify_risk[,"marital_status"],n.classify_risk[,3],classify_risk[,"risk"])

colnames(n.classify_risk) <- colnames(classify_risk)

head(n.classify_risk)

classify_risk.training <- n.classify_risk[ind == 1, 1:6]
classify_risk.test <- n.classify_risk[ind == 2, 1:6]

## Label Split
classify_risk.trainLabels <- n.classify_risk[ind == 1, 6]
classify_risk.testLabels <- n.classify_risk[ind == 2, 6]
```

```{r, warning=FALSE, message=FALSE}
classify_risk_pred <- knn(train = classify_risk.training[,c(2,3,5)], test =
                            classify_risk.test[,c(2,3,5)], cl =
                            classify_risk.trainLabels,k = 5)

results = data.frame(classify_risk_pred, classify_risk.testLabels)
table(results)

# install.packages('caret')
require(caret)
# install.packages('e1071')
require(e1071)
confusionMatrix(table(results))

```

```{r, warning=FALSE, message=FALSE}

test_classify_risk <- read.csv("classifyrisk.csv", header=TRUE, sep=",", dec=".")

n.test_classify_risk <- data.frame(sapply(test_classify_risk[,c(2,3,5)], function(x) {
  (x - min(x))/(max(x) - min(x))
}))

classify_risk_pred.test <- n.test_classify_risk
head(classify_risk_pred.test)

classify_test_result <- knn(train = classify_risk.training[,c(2,3,5)], test=classify_risk_pred.test, cl = classify_risk[ind == 1, 6], k = 5)

(classify_test_result)

test_classify_risk[,"risk"] <- classify_test_result

test_classify_risk
```





